name: PluginTest
version: 1.0
api-version: 1.20
main: fr.raillou.plugin.Main
commands:
  setspawn:
    description: Definit un point de spawn
    usage: Erreur dans la commande
  spawn:
    description: Teleporte au spawn
    usage: Erreur dans la commande